name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.4.2
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  googleapis: ^10.0.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  meta: ^1.9.0
  collection: ^1.17.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.22.2
