name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.4.0
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  meta: ^1.7.0
  collection: ^1.16.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.20.2
